services:
  backend:
    build: ./backend
    ports:
      - '3002:3001'
    volumes:
      - ./backend/db.sqlite:/app/db.sqlite

  frontend:
    build: ./frontend
    ports:
      - '3003:80'

    # depends_on:
    #   - backend
