version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3002:3001'
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite:/app/db.sqlite

  frontend:
    build: ./frontend
    ports:
      - '3003:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
